//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UV_DLP_3D_Printer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UV_DLP_3D_Printer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap animatedTurningHelix {
            get {
                object obj = ResourceManager.GetObject("animatedTurningHelix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;fontMetrics file=&quot;Arial18.png&quot;&gt;
        ///  &lt;character key=&quot;32&quot;&gt;
        ///    &lt;x&gt;0&lt;/x&gt;
        ///    &lt;y&gt;0&lt;/y&gt;
        ///    &lt;width&gt;7&lt;/width&gt;
        ///    &lt;height&gt;21&lt;/height&gt;
        ///  &lt;/character&gt;
        ///  &lt;character key=&quot;33&quot;&gt;
        ///    &lt;x&gt;7&lt;/x&gt;
        ///    &lt;y&gt;0&lt;/y&gt;
        ///    &lt;width&gt;5&lt;/width&gt;
        ///    &lt;height&gt;21&lt;/height&gt;
        ///  &lt;/character&gt;
        ///  &lt;character key=&quot;34&quot;&gt;
        ///    &lt;x&gt;12&lt;/x&gt;
        ///    &lt;y&gt;0&lt;/y&gt;
        ///    &lt;width&gt;8&lt;/width&gt;
        ///    &lt;height&gt;21&lt;/height&gt;
        ///  &lt;/character&gt;
        ///  &lt;character key=&quot;35&quot;&gt;
        ///    &lt;x&gt;20&lt;/x&gt;
        ///    &lt;y&gt;0&lt;/y&gt;
        ///    &lt;width&gt;12&lt;/width&gt;
        ///    &lt;height&gt;21&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Arial18_metrics {
            get {
                return ResourceManager.GetString("Arial18_metrics", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap bfzn_003 {
            get {
                object obj = ResourceManager.GetObject("bfzn_003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bfzn_004 {
            get {
                object obj = ResourceManager.GetObject("bfzn_004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bfzn_006 {
            get {
                object obj = ResourceManager.GetObject("bfzn_006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap butMinus {
            get {
                object obj = ResourceManager.GetObject("butMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttAddSupport {
            get {
                object obj = ResourceManager.GetObject("buttAddSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttArrange {
            get {
                object obj = ResourceManager.GetObject("buttArrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttAutoDown {
            get {
                object obj = ResourceManager.GetObject("buttAutoDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttAutoSupport {
            get {
                object obj = ResourceManager.GetObject("buttAutoSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttBoundingBox {
            get {
                object obj = ResourceManager.GetObject("buttBoundingBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttCenter {
            get {
                object obj = ResourceManager.GetObject("buttCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttChecked {
            get {
                object obj = ResourceManager.GetObject("buttChecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttConnect {
            get {
                object obj = ResourceManager.GetObject("buttConnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttConsole {
            get {
                object obj = ResourceManager.GetObject("buttConsole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttDisconnect {
            get {
                object obj = ResourceManager.GetObject("buttDisconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttDownward {
            get {
                object obj = ResourceManager.GetObject("buttDownward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttGear {
            get {
                object obj = ResourceManager.GetObject("buttGear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttGoZHome {
            get {
                object obj = ResourceManager.GetObject("buttGoZHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttHomeZ {
            get {
                object obj = ResourceManager.GetObject("buttHomeZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttInchMm {
            get {
                object obj = ResourceManager.GetObject("buttInchMm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttIntersect {
            get {
                object obj = ResourceManager.GetObject("buttIntersect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttMachineConfig {
            get {
                object obj = ResourceManager.GetObject("buttMachineConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttMachineControl {
            get {
                object obj = ResourceManager.GetObject("buttMachineControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttMeshTools {
            get {
                object obj = ResourceManager.GetObject("buttMeshTools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttMirror {
            get {
                object obj = ResourceManager.GetObject("buttMirror", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttMmInch {
            get {
                object obj = ResourceManager.GetObject("buttMmInch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttModifySupport {
            get {
                object obj = ResourceManager.GetObject("buttModifySupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttMove {
            get {
                object obj = ResourceManager.GetObject("buttMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttOinfo {
            get {
                object obj = ResourceManager.GetObject("buttOinfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttOnPlatform {
            get {
                object obj = ResourceManager.GetObject("buttOnPlatform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttOpenClose {
            get {
                object obj = ResourceManager.GetObject("buttOpenClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttOpenFile {
            get {
                object obj = ResourceManager.GetObject("buttOpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPause {
            get {
                object obj = ResourceManager.GetObject("buttPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPCone {
            get {
                object obj = ResourceManager.GetObject("buttPCone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPCube {
            get {
                object obj = ResourceManager.GetObject("buttPCube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPCylinder {
            get {
                object obj = ResourceManager.GetObject("buttPCylinder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPlay {
            get {
                object obj = ResourceManager.GetObject("buttPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPlus {
            get {
                object obj = ResourceManager.GetObject("buttPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPrevDisp {
            get {
                object obj = ResourceManager.GetObject("buttPrevDisp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttProjector {
            get {
                object obj = ResourceManager.GetObject("buttProjector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttProjOff {
            get {
                object obj = ResourceManager.GetObject("buttProjOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttProjOn {
            get {
                object obj = ResourceManager.GetObject("buttProjOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPSphere {
            get {
                object obj = ResourceManager.GetObject("buttPSphere", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttPTorus {
            get {
                object obj = ResourceManager.GetObject("buttPTorus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttRedo {
            get {
                object obj = ResourceManager.GetObject("buttRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttRotate {
            get {
                object obj = ResourceManager.GetObject("buttRotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSave {
            get {
                object obj = ResourceManager.GetObject("buttSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttScale {
            get {
                object obj = ResourceManager.GetObject("buttScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttScene {
            get {
                object obj = ResourceManager.GetObject("buttScene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSendGcode {
            get {
                object obj = ResourceManager.GetObject("buttSendGcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttShowslice {
            get {
                object obj = ResourceManager.GetObject("buttShowslice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttShowsliceh {
            get {
                object obj = ResourceManager.GetObject("buttShowsliceh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSlice {
            get {
                object obj = ResourceManager.GetObject("buttSlice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSliceConf {
            get {
                object obj = ResourceManager.GetObject("buttSliceConf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttStateTrig {
            get {
                object obj = ResourceManager.GetObject("buttStateTrig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttStop {
            get {
                object obj = ResourceManager.GetObject("buttStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSubtract {
            get {
                object obj = ResourceManager.GetObject("buttSubtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSupBase {
            get {
                object obj = ResourceManager.GetObject("buttSupBase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttSupport {
            get {
                object obj = ResourceManager.GetObject("buttSupport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttTemperature {
            get {
                object obj = ResourceManager.GetObject("buttTemperature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttTransparent {
            get {
                object obj = ResourceManager.GetObject("buttTransparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttTreeview {
            get {
                object obj = ResourceManager.GetObject("buttTreeview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttUndo {
            get {
                object obj = ResourceManager.GetObject("buttUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttUnion {
            get {
                object obj = ResourceManager.GetObject("buttUnion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttV {
            get {
                object obj = ResourceManager.GetObject("buttV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttView {
            get {
                object obj = ResourceManager.GetObject("buttView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttViewDown {
            get {
                object obj = ResourceManager.GetObject("buttViewDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttViewGcode {
            get {
                object obj = ResourceManager.GetObject("buttViewGcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttViewModel {
            get {
                object obj = ResourceManager.GetObject("buttViewModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttViewSlice {
            get {
                object obj = ResourceManager.GetObject("buttViewSlice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttX {
            get {
                object obj = ResourceManager.GetObject("buttX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap buttZeroZ {
            get {
                object obj = ResourceManager.GetObject("buttZeroZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap checkRect {
            get {
                object obj = ResourceManager.GetObject("checkRect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Connect {
            get {
                object obj = ResourceManager.GetObject("Connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon cwlogo_dl {
            get {
                object obj = ResourceManager.GetObject("cwlogo_dl", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cwlogo_round {
            get {
                object obj = ResourceManager.GetObject("cwlogo_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cwtexture1 {
            get {
                object obj = ResourceManager.GetObject("cwtexture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///cwtexture1.png
        ///format: RGBA8888
        ///filter: Linear,Linear
        ///repeat: none
        ///Arial18
        ///  rotate: false
        ///  xy: 0, 116
        ///  size: 208, 126
        ///  orig: 208, 126
        ///  offset: 0, 0
        ///  index: -1
        ///WarnWall
        ///  rotate: false
        ///  xy: 210, 114
        ///  size: 128, 128
        ///  orig: 128, 128
        ///  offset: 0, 0
        ///  index: -1
        ///cwlogo_round
        ///  rotate: false
        ///  xy: 0, 14
        ///  size: 100, 100
        ///  orig: 100, 100
        ///  offset: 0, 0
        ///  index: -1
        ///cwlogo_tr
        ///  rotate: false
        ///  xy: 340, 154
        ///  size: 88, 88
        ///  orig: 88, 88
        ///  offset: 0, 0
        ///  index: -1
        ///cwpanel
        ///  rotate: false
        ///  xy: 102, 34
        ///  size: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cwtexture1_index {
            get {
                return ResourceManager.GetString("cwtexture1_index", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Disconnect {
            get {
                object obj = ResourceManager.GetObject("Disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap donate {
            get {
                object obj = ResourceManager.GetObject("donate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Donate1 {
            get {
                object obj = ResourceManager.GetObject("Donate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Down1 {
            get {
                object obj = ResourceManager.GetObject("Down1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Down1Blue {
            get {
                object obj = ResourceManager.GetObject("Down1Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;GuiConfig FileVersion=&quot;1&quot;&gt;
        ///	&lt;buttons&gt;
        ///		&lt;style backcolor=&quot;RoyalBlue&quot; hovercolor=&quot;White&quot; forecolor=&quot;#DCDCDC&quot; checkcolor=&quot;#DCDCDC&quot; presscolor=&quot;White&quot; nimages=&quot;1&quot; pressscale=&quot;92&quot; gl=&quot;false&quot;/&gt;
        ///		&lt;style name=&quot;glbutt1&quot; backcolor=&quot;Transparent&quot; hovercolor=&quot;Navy&quot; forecolor=&quot;Navy&quot; checkcolor=&quot;Navy&quot; presscolor=&quot;White&quot; nimages=&quot;1&quot; hoverscale=&quot;106&quot; gl=&quot;true&quot;/&gt;
        ///		&lt;button name=&quot;home&quot; dock=&quot;tr&quot; x=&quot;10&quot; y=&quot;100&quot; image=&quot;glButtHome1&quot; w=&quot;48&quot; h=&quot;48&quot; style=&quot;glbutt1&quot;/&gt;
        ///		&lt;button name=&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GuiConfig {
            get {
                return ResourceManager.GetString("GuiConfig", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap homeButt {
            get {
                object obj = ResourceManager.GetObject("homeButt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Left1Blue {
            get {
                object obj = ResourceManager.GetObject("Left1Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Load {
            get {
                object obj = ResourceManager.GetObject("Load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_cent {
            get {
                object obj = ResourceManager.GetObject("mc_cent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_centn {
            get {
                object obj = ResourceManager.GetObject("mc_centn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_home {
            get {
                object obj = ResourceManager.GetObject("mc_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_onoff {
            get {
                object obj = ResourceManager.GetObject("mc_onoff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_onoffbgnd {
            get {
                object obj = ResourceManager.GetObject("mc_onoffbgnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_onoffslide {
            get {
                object obj = ResourceManager.GetObject("mc_onoffslide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_px0 {
            get {
                object obj = ResourceManager.GetObject("mc_px0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_px1 {
            get {
                object obj = ResourceManager.GetObject("mc_px1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_px2 {
            get {
                object obj = ResourceManager.GetObject("mc_px2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_px3 {
            get {
                object obj = ResourceManager.GetObject("mc_px3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_shuttclose {
            get {
                object obj = ResourceManager.GetObject("mc_shuttclose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_shuttopen {
            get {
                object obj = ResourceManager.GetObject("mc_shuttopen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_temper {
            get {
                object obj = ResourceManager.GetObject("mc_temper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_tpoint {
            get {
                object obj = ResourceManager.GetObject("mc_tpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_trcorner {
            get {
                object obj = ResourceManager.GetObject("mc_trcorner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_uparrow {
            get {
                object obj = ResourceManager.GetObject("mc_uparrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_uparrown {
            get {
                object obj = ResourceManager.GetObject("mc_uparrown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_z0 {
            get {
                object obj = ResourceManager.GetObject("mc_z0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_z1 {
            get {
                object obj = ResourceManager.GetObject("mc_z1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_z2 {
            get {
                object obj = ResourceManager.GetObject("mc_z2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_z3 {
            get {
                object obj = ResourceManager.GetObject("mc_z3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mc_ztop {
            get {
                object obj = ResourceManager.GetObject("mc_ztop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap move {
            get {
                object obj = ResourceManager.GetObject("move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap move_bgnd {
            get {
                object obj = ResourceManager.GetObject("move_bgnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap niceAnimatedTriangles {
            get {
                object obj = ResourceManager.GetObject("niceAnimatedTriangles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap paypal_donate_button {
            get {
                object obj = ResourceManager.GetObject("paypal-donate-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap position {
            get {
                object obj = ResourceManager.GetObject("position", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Refresh_icon {
            get {
                object obj = ResourceManager.GetObject("Refresh-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Right1Blue {
            get {
                object obj = ResourceManager.GetObject("Right1Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rounded_blue_home_button_4805 {
            get {
                object obj = ResourceManager.GetObject("rounded_blue_home_button_4805", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SelOutline {
            get {
                object obj = ResourceManager.GetObject("SelOutline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap SelShaded {
            get {
                object obj = ResourceManager.GetObject("SelShaded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap slice {
            get {
                object obj = ResourceManager.GetObject("slice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Splash1 {
            get {
                object obj = ResourceManager.GetObject("Splash1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap turningGear {
            get {
                object obj = ResourceManager.GetObject("turningGear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Up1 {
            get {
                object obj = ResourceManager.GetObject("Up1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Up1Blue {
            get {
                object obj = ResourceManager.GetObject("Up1Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
